/**
 * The shapes the API answers with.
 *
 * Hand-written rather than generated, and deliberately partial: only the
 * fields the screens read are here. A generated client would carry every
 * field of every response and would still have to be regenerated by somebody
 * who noticed the contract moved — which is the same amount of noticing, with
 * a build step in front of it.
 */

export type Page<T> = {
  items: T[]
  page: number
  page_size: number
  total: number
  has_more: boolean
}

export type Message = { message: string }

// ------------------------------------------------------------------- the room

export type LocationKind =
  | "bin"
  | "receiving"
  | "packing"
  | "courier"
  | "damaged"
  | "returns"

export type Location = {
  id: number
  code: string
  kind: LocationKind
  rack: string | null
  column_no: number | null
  row_no: number | null
  capacity: number
  is_active: boolean
  note: string
  products: number
  units: number
  fill_percent: number
  oldest_minutes: number
}

export type CellContent = {
  variant_id: number
  product_id: number
  product_title: string
  variant_label: string
  sku: string
  barcode: string
  qty: number
  minutes_here: number
}

export type LocationDetail = Location & { contents: CellContent[] }

export type ShelfMap = {
  cells: Location[]
  staging: Location[]
  couriers: Location[]
}

export type Placement = { location_id: number; code: string; qty: number }

export type WhereIs = {
  variant_id: number
  product_id: number
  product_title: string
  variant_label: string
  sku: string
  barcode: string
  places: Placement[]
}

export type PutawayLine = CellContent & { suggestion: string }

// --------------------------------------------------------------- market runs

export type SupplyStatus = "draft" | "received" | "cancelled"

export type SupplyLine = {
  id: number
  variant_id: number
  sku: string
  variant_label: string
  product_title: string
  quantity: number
  unit_cost: number
  line_cost: number
}

export type Supply = {
  id: number
  code: string
  status: SupplyStatus
  place: string
  transport_cost: number
  buyer: string
  note: string
  lines: SupplyLine[]
  total_cost: number
  declared_at: string
  received_at: string | null
  age_minutes: number
}

// ------------------------------------------------------------------- picking

export type PickStatus = "waiting" | "picking" | "picked"

export type PickLine = {
  id: number
  variant_id: number
  product_title: string
  colour: string
  size: string
  variant_label: string
  sku: string
  barcode: string
  location_id: number
  location_code: string
  qty: number
  picked_qty: number
  walk_order: number
  mixed_cell: boolean
}

export type PickTask = {
  id: number
  order_id: number
  order_code: string
  status: PickStatus
  picker: string
  lines: PickLine[]
  created_at: string
  taken_at: string | null
  finished_at: string | null
  age_minutes: number
}

// ------------------------------------------------------------------ counting

export type CountLine = {
  variant_id: number
  product_title: string
  variant_label: string
  sku: string
  barcode: string
  expected_qty: number
  counted_qty: number
}

export type StockCount = {
  id: number
  location_id: number
  location_code: string
  status: "open" | "closed"
  counter: string
  note: string
  lines: CountLine[]
  started_at: string
  closed_at: string | null
}

// -------------------------------------------------------------------- labels

export type ProductLabel = {
  variant_id: number
  product_title: string
  variant_label: string
  sku: string
  barcode: string
  price: number
}

export type CellLabel = {
  code: string
  rack: string | null
  column_no: number | null
  row_no: number | null
}

export type LabelSheet = { products: ProductLabel[]; cells: CellLabel[] }

// ----------------------------------------------------------------- catalogue

export type ProductStatus = "draft" | "active" | "archived"

export type AdminProduct = {
  id: number
  sku: string
  title: string
  subtitle: string
  status: ProductStatus
  next_statuses: ProductStatus[]
  category_slug: string
  brand_slug: string | null
  price: number
  old_price: number | null
  stock_left: number
  image_count: number
  variant_count: number
  created_at: string
}

export type AdminVariant = {
  id: number
  colour: string
  colour_hex: string
  size: string
  label: string
  sku: string
  barcode: string
  price: number
  sort: number
  stock_left: number
  in_stock: boolean
  can_delete: boolean
  blocked_reason: string
}

export type AdminImage = { id: number; url: string; sort: number; colour: string }

export type AdminCategory = {
  id: number
  slug: string
  name: string
  subtitle: string
  parent_slug: string | null
  product_count: number
}

export type Media = { media_url: string; width: number; height: number; bytes: number }
