/**
 * The shapes the API answers with.
 *
 * Hand-written rather than generated, and deliberately partial: only the
 * fields the screens read are here. A generated client would carry every
 * field of every response and would still have to be regenerated by somebody
 * who noticed the contract moved — which is the same amount of noticing, with
 * a build step in front of it.
 */

export type Page<T> = {
  items: T[]
  page: number
  page_size: number
  total: number
  has_more: boolean
}

export type Message = { message: string }

// ------------------------------------------------------------------- the room

export type LocationKind =
  | "bin"
  | "receiving"
  | "packing"
  | "courier"
  | "damaged"
  | "returns"

export type Location = {
  id: number
  code: string
  kind: LocationKind
  rack: string | null
  column_no: number | null
  row_no: number | null
  capacity: number
  /** How many more this cell is meant to take. `null` is a cell with no
   *  stated capacity — an unmeasured one, not a roomy one. */
  free: number | null
  is_active: boolean
  note: string
  products: number
  units: number
  /** Against capacity, and **not capped at a hundred**: a cell holding 65 of
   *  a stated 60 reads 108, because the figure exists to say exactly that. */
  fill_percent: number
  oldest_minutes: number
}

/** One cell of a plan, and what the plan would put in it. */
export type PutawayLine = {
  code: string
  quantity: number
  free: number | null
  units: number
  holds_this_model: boolean
}

/**
 * Where N pieces would go if nobody thought about it.
 *
 * The model's own cells first — one model per cell is the discipline — each
 * to its free room, then the emptiest cells nearest them. `over_capacity`
 * means the last line is more than the room it is going into, which happens
 * because the goods are standing on the floor: a plan that stops short of the
 * quantity is a plan that does not say where the rest went.
 */
export type PutawayPlan = {
  quantity: number
  lines: PutawayLine[]
  over_capacity: boolean
  message: string
}

export type CellContent = {
  variant_id: number
  product_id: number
  product_title: string
  variant_label: string
  sku: string
  barcode: string
  qty: number
  minutes_here: number
}

export type LocationDetail = Location & { contents: CellContent[] }

export type ShelfMap = {
  cells: Location[]
  staging: Location[]
  couriers: Location[]
}

export type Placement = { location_id: number; code: string; qty: number }

export type WhereIs = {
  variant_id: number
  product_id: number
  product_title: string
  variant_label: string
  sku: string
  barcode: string
  places: Placement[]
}

// --------------------------------------------------------------- market runs

export type SupplyStatus = "draft" | "received" | "cancelled"

export type SupplyLine = {
  id: number
  variant_id: number
  sku: string
  variant_label: string
  product_title: string
  quantity: number
  unit_cost: number
  line_cost: number
}

export type Supply = {
  id: number
  code: string
  status: SupplyStatus
  place: string
  transport_cost: number
  buyer: string
  note: string
  lines: SupplyLine[]
  total_cost: number
  declared_at: string
  received_at: string | null
  age_minutes: number
}

// ------------------------------------------------------------------- picking

export type PickStatus = "waiting" | "picking" | "picked"

export type PickLine = {
  id: number
  variant_id: number
  product_title: string
  colour: string
  size: string
  variant_label: string
  sku: string
  barcode: string
  location_id: number
  location_code: string
  qty: number
  picked_qty: number
  walk_order: number
  mixed_cell: boolean
}

export type PickTask = {
  id: number
  order_id: number
  order_code: string
  status: PickStatus
  picker: string
  lines: PickLine[]
  created_at: string
  taken_at: string | null
  finished_at: string | null
  age_minutes: number
}

/** An order waiting for the board: not a task yet, see `GET /warehouse/pick/waiting`. */
export type PickWaiting = {
  order_id: number
  order_code: string
  items_count: number
  items_summary: string
  delivery_day: string | null
  delivery_window: string
  age_minutes: number
}

// ------------------------------------------------------------------ counting

export type CountLine = {
  variant_id: number
  product_title: string
  variant_label: string
  sku: string
  barcode: string
  expected_qty: number
  counted_qty: number
}

export type StockCount = {
  id: number
  location_id: number
  location_code: string
  status: "open" | "closed"
  counter: string
  note: string
  lines: CountLine[]
  started_at: string
  closed_at: string | null
}

// -------------------------------------------------------------------- labels

export type ProductLabel = {
  variant_id: number
  product_title: string
  variant_label: string
  sku: string
  barcode: string
  price: number
}

export type CellLabel = {
  code: string
  rack: string | null
  column_no: number | null
  row_no: number | null
}

export type LabelSheet = { products: ProductLabel[]; cells: CellLabel[] }

// ----------------------------------------------------------------- catalogue

export type ProductStatus = "draft" | "active" | "archived"

/** One reason a card is not in the shop. The key picks the control, the label
 *  is the server's wording — the browser keeps neither the rule nor the words. */
export type Gap = {
  key:
    | "needs_category"
    | "needs_price"
    | "needs_photo"
    | "needs_subtitle"
    | "needs_description"
    | "needs_specs"
    | "needs_more_photos"
  label: string
}

export type AdminProduct = {
  id: number
  sku: string
  title: string
  subtitle: string
  /** The receiving desk's word for it — "Krossovka". Not the category. */
  kind: string
  status: ProductStatus
  next_statuses: ProductStatus[]
  /** Absent on a card written with the sack open and not yet filed. */
  category_slug: string | null
  brand_slug: string | null
  /** The identification photograph, over the open sack. Never shown to a
   *  customer: it is what tells two black trainers apart in a search result. */
  snapshot_url: string
  /** The catalogue photograph the customer meets first — the cover of the
   *  card's first colour, by the same ordering the apps read. `""` when the
   *  card has none, which is the `Rasmsiz` queue. */
  cover_url: string
  unready: Gap[]
  /** What it is missing to read like a shop rather than a stub. Not a gate. */
  listing_gaps: Gap[]
  price: number
  old_price: number | null
  /** What these last cost at the market. 0 means nothing is booked in yet. */
  last_cost: number
  stock_left: number
  /** The cells of this card that are empty — `Qora`, or `Qora / 42`. */
  sold_out: string[]
  image_count: number
  variant_count: number
  created_at: string
}

/** The receiving desk's chips, learned from what came through the door. */
/** One card with everything the editor binds to. */
export type AdminProductDetail = AdminProduct & {
  description: string
  badge: string | null
  warranty: string | null
  is_original: boolean
  free_delivery: boolean
  next_day_delivery: boolean
}

export type Spec = { key: string; value: string }

export type Vocab = {
  kinds: string[]
  brands: string[]
  colours: string[]
  /** Keyed by kind: trainers in 40-45, shirts in S-XXL. */
  sizes: Record<string, string[]>
  /** The kinds that have no sizes at all — a cap, a bag, a wristwatch. */
  sizeless: string[]
  /** The specification rows written against this kind last time, so the table
   *  arrives already named rather than empty. */
  spec_keys: Record<string, string[]>
}

export type AdminVariant = {
  id: number
  colour: string
  colour_hex: string
  size: string
  label: string
  sku: string
  barcode: string
  price: number
  sort: number
  stock_left: number
  in_stock: boolean
  /** Out of the shop window without being erased. A size received by mistake
   *  cannot be deleted — the ledger points at it — and would otherwise be
   *  offered, struck through, for the life of the card. */
  retired: boolean
  can_delete: boolean
  blocked_reason: string
}

export type AdminImage = { id: number; url: string; sort: number; colour: string }

export type AdminCategory = {
  id: number
  slug: string
  name: string
  subtitle: string
  parent_slug: string | null
  product_count: number
  /** Why a delete would be refused, without having to try it: a category with
   *  cards filed under it, or with categories beneath it, is load-bearing. */
  child_count: number
}

/** What building a shelf unit answers with: the letter, and how many cells. */
export type Rack = { rack: string; cells: number; message: string }

/** A cell taken out of the room, and whether its row went with it.
 *
 *  `erased` is reported, never asked for: the server deletes the row when
 *  nothing in the ledger names the cell and keeps it invisibly when a
 *  movement or a stocktake does. Both are gone from the map, which is why no
 *  screen branches on it — it is only there for the sentence afterwards. */
export type CellRemoved = { code: string; erased: boolean; message: string }

// -------------------------------------------------------------------- returns

export type ReturnStatus = "submitted" | "approved" | "rejected" | "refunded"
/** `null` is the honest third state: nobody has opened the parcel yet. */
export type ReturnInspection = "ok" | "damaged" | null

/**
 * One customer asking for their money back.
 *
 * `next_statuses` is the server's answer about what may happen next, and the
 * screen draws its buttons from it rather than keeping its own copy of the
 * rules — `submitted` decides, `approved` refunds, and the other two are
 * where a return stops.
 *
 * The inspection is a **separate axis** from the status: the warehouse opens
 * the parcel and says whole or damaged, which may happen before or after the
 * money goes back, and `relisted` says whether the goods reached a shelf
 * again.
 */
export type StaffReturn = {
  id: number
  order_id: number
  order_code: string
  order_item_id: number | null
  customer_name: string
  customer_phone: string
  reason: string
  comment: string
  photos: string[]
  status: ReturnStatus
  /** The sentence the customer reads. A rejection's reason becomes this. */
  resolution: string
  refund_amount: number
  next_statuses: ReturnStatus[]
  created_at: string
  product_title: string
  inspection: ReturnInspection
  inspection_label: string
  inspection_note: string
  inspected_at: string | null
  /** The room has moved for this request — **not** "it went back on sale".
   *  A damaged parcel sets it too; it went to the damaged corner. Read
   *  `inspection` to say where it landed. It is the once-only guard that
   *  makes inspecting and refunding safe in either order. */
  relisted: boolean
}

// --------------------------------------------------------------- one order

export type OrderItem = {
  id: number
  product_id: number | null
  title: string
  image_url: string
  colour: string
  size: string
  variant_label: string
  unit_price: number
  quantity: number
  line_total: number
  reviewed: boolean
}

/** A step of the order's life. `happened_at` null means "not reached yet" —
 *  the four flow rows are written blank at checkout and filled in as they
 *  happen, so the timeline exists before the order has lived it. */
export type OrderEvent = {
  status: OrderStatus
  title: string
  happened_at: string | null
  note: string
  done: boolean
}

/**
 * One knock at one door.
 *
 * The courier's list carries a count; an operator is answering a different
 * question — has this been tried enough to give up on — and a number cannot
 * answer it. Three knocks at one wrong buzzer and three on three days are the
 * same count and different decisions.
 */
export type DeliveryAttempt = {
  id: number
  order_id: number
  order_code: string
  courier_name: string
  result: "delivered" | "failed"
  reason: string
  recipient_name: string
  photo_url: string | null
  cash_collected: number
  happened_at: string
}

/** The order in full — the screen somebody opens with the customer on the
 *  telephone. `attempts` is populated here and nowhere else. */
export type OrderDetail = {
  id: number
  code: string
  status: OrderStatus
  status_label: string
  total: number
  items_count: number
  preview_images: string[]
  eta_label: string
  created_at: string
  can_cancel: boolean
  can_track: boolean
  delivery_kind: "courier" | "pickup"
  address_line: string
  address_meta: string
  delivery_day: string | null
  /** Bare `"09:00"` wall-clock strings, **not instants** — they are the window
   *  as it was booked. Passing one to `time()` silently yields an empty
   *  string and the window renders as a lone dash. */
  delivery_start: string | null
  delivery_end: string | null
  payment_method: "card" | "cash"
  payment_label: string
  paid: boolean
  recipient_name: string
  recipient_phone: string
  subtotal: number
  delivery_fee: number
  discount: number
  items: OrderItem[]
  events: OrderEvent[]
  attempts: DeliveryAttempt[]
}

/** A curated cancel or return reason. Five of each, in a table, and the panel
 *  has been writing free text beside them. */
export type Reason = { id: number; label: string; requires_comment: boolean }

// --------------------------------------------------------- pickup runs

export type PickupRunStatus = "open" | "collected" | "received" | "cancelled"

/** One door on a collection round. `collected` null is the third state:
 *  nobody has tried yet. */
export type PickupLine = {
  id: number
  return_request_id: number
  order_code: string
  customer_name: string
  customer_phone: string
  address_line: string
  reason: string
  product_title: string
  collected: boolean | null
  note: string
  photo_url: string | null
  attempted_at: string | null
}

/**
 * A van sent inward: approved returns collected from customers' doors.
 *
 * `collected` and `received` are two different people's claims — the courier
 * says they have the goods, the warehouse says they arrived. Collapsing them
 * would make "he collected it and it never reached us" unsayable.
 */
export type PickupRun = {
  id: number
  code: string
  courier_id: number
  courier_name: string
  status: PickupRunStatus
  next_statuses: PickupRunStatus[]
  created_at: string
  collected_at: string | null
  received_at: string | null
  note: string
  lines: PickupLine[]
}

/**
 * Where one variant stands: what the ledger says, what is promised, and what
 * is left to sell.
 *
 * `on_hand` is **everything in the building** — the damaged corner and the
 * uninspected returns are in the building too — so a garment moved to BRAK
 * does not change it. `sellable` is the figure that moves, and it is the one
 * to quote back after a damage.
 */
export type Shelf = {
  variant_id: number
  variant_label: string
  on_hand: number
  reserved: number
  sellable: number
  places: { location_id: number; code: string; qty: number }[]
}

export type Media = { media_url: string; width: number; height: number; bytes: number }

// -------------------------------------------------------------------- orders

export type OrderStatus =
  | "placed"
  | "packing"
  | "shipped"
  | "delivered"
  | "cancelled"
  | "returned"

export type StaffOrder = {
  id: number
  code: string
  status: OrderStatus
  status_label: string
  customer_name: string
  customer_phone: string
  delivery_kind: string
  address_line: string
  delivery_day: string | null
  delivery_window: string
  items_count: number
  items_summary: string
  total: number
  paid: boolean
  next_statuses: OrderStatus[]
  courier_id: number | null
  courier_name: string
  courier_sequence: number
  created_at: string
}

// ------------------------------------------------------------------- people

/**
 * Every role there is.
 *
 * `seller` is gone from the server's enum — publishing belongs to the admin
 * now — so it is gone from here too: a union wider than the server's is a
 * role chooser offering a job that no longer exists.
 */
export type UserRole = "admin" | "warehouse" | "courier" | "customer"

/**
 * The same four roles, in the words the office says them in.
 *
 * Here rather than on a screen because three screens print them — the staff
 * directory, the journal's actor column and its actor chooser — and a word
 * kept next to its own union cannot drift from it. `admin` and
 * "Administrator" are one fact in two alphabets, not a type and a decoration.
 */
export const ROLE_LABEL: Record<UserRole, string> = {
  admin: "Administrator",
  warehouse: "Ombor",
  courier: "Kuryer",
  customer: "Mijoz",
}

/** Any account at all — what `GET /admin/users` answers with. Customers are
 *  in it, which is why it is a lookup by phone and not a screen. */
export type StaffUser = {
  id: number
  phone: string
  full_name: string
  role: UserRole
  is_active: boolean
  created_at: string
}

/**
 * A colleague, from `GET /admin/staff` — never a customer.
 *
 * `last_seen` is derived from the refresh tokens the account still holds, so
 * it means "there is a live session" and not "they were at their desk at
 * 14:02". A screen that labels it as an exact time is a screen that will be
 * used to argue about somebody's hours.
 */
export type StaffMember = StaffUser & {
  email: string | null
  last_seen: string | null
}

export type CustomerRow = {
  id: number
  phone: string
  full_name: string
  email: string | null
  is_active: boolean
  created_at: string
  orders_count: number
  /** Delivered orders only — a promise and a cancellation are not money. */
  spent: number
  last_order_at: string | null
  last_seen: string | null
}

export type CustomerOrder = {
  id: number
  code: string
  status: OrderStatus
  status_label: string
  total: number
  created_at: string
}

export type CustomerAddress = {
  id: number
  title: string
  icon: string
  badge: string | null
  line: string
  city: string
  meta: string
  floor: string | null
  apartment: string | null
  entrance_code: string | null
  comment: string | null
  is_default: boolean
}

export type CustomerCard = {
  id: number
  brand: string
  last4: string
  holder: string
  expiry: string
  status: "active" | "expired" | "blocked"
  is_default: boolean
}

export type CustomerCartLine = {
  id: number
  product_id: number
  title: string
  image_url: string | null
  variant_label: string
  unit_price: number
  quantity: number
  selected: boolean
  in_stock: boolean
  stock_left: number
  line_total: number
}

/** One customer, in one response — the screen opened while they are on the
 *  telephone, so six requests would be six things to wait through. */
export type CustomerDetail = CustomerRow & {
  language: string
  birth_date: string | null
  favorites_count: number
  addresses: CustomerAddress[]
  cards: CustomerCard[]
  orders: CustomerOrder[]
  cart: CustomerCartLine[]
}

/**
 * One line of the trail, with the actor already resolved.
 *
 * `actor_role` is the authority the change was made under, off the row
 * itself — not whatever that person's role happens to be today.
 */
export type AuditRow = {
  id: number
  created_at: string
  actor_id: number | null
  actor_name: string
  actor_phone: string
  actor_role: UserRole | null
  action: string
  entity: string
  entity_id: number | null
  field: string
  old_value: string | null
  new_value: string | null
  note: string
}

// ----------------------------------------------------------------- the round

export type CourierOrder = {
  id: number
  code: string
  sequence: number
  status: OrderStatus
  recipient_name: string
  recipient_phone: string
  address_line: string
  address_meta: string
  delivery_kind: string
  delivery_day: string | null
  delivery_window: string
  items_count: number
  total: number
  payment_method: "card" | "cash"
  cash_due: number
  attempts: number
  last_failure: string
  /**
   * Where the door is, when anybody knows.
   *
   * Nullable and *staying* nullable: every order placed before the shop began
   * recording a pin has none and never will. A stop without one is still a
   * stop — it keeps its place in the round and the list says
   * `xaritada belgilanmagan` rather than quietly disappearing off a map the
   * courier is steering by.
   *
   * Optional on the type as well as nullable, because the field is landing in
   * `CourierOrderOut` alongside this work: an older server answers without it
   * and the app must not fall over reading a round from one.
   */
  latitude?: number | null
  longitude?: number | null
}

export type CourierEarnings = {
  delivered_today: number
  delivered_month: number
  delivered_total: number
  fee_per_delivery: number
  earned_today: number
  earned_month: number
  earned_total: number
  /** Taken at doors less handed back, floored at nought. The two sides are
   *  beside it because a courier querying the figure wants to see the
   *  subtraction rather than be told the answer. */
  cash_on_hand: number
  cash_collected: number
  cash_handed_in: number
  failed_attempts: number
}

/** Somebody at the warehouse a courier may hand the day's takings to. The
 *  write refuses anybody else, so the picker offers exactly this list. */
export type CashReceiver = {
  id: number
  full_name: string
  phone: string
  role: UserRole
}

/** One receipt for cash going back over the counter. */
export type CashHandover = {
  id: number
  amount: number
  courier_id: number
  courier_name: string
  received_by_id: number
  received_by_name: string
  note: string
  happened_at: string
  /** What the courier is carrying **now** — on the reply to the hand-over
   *  itself that is the figure after it, which is why the screen can redraw
   *  without a second round trip. */
  cash_on_hand: number
}

// ----------------------------------------------------------------- dashboard

export type DashboardTile = {
  key: string
  label: string
  value: number
  hint: string
  href: string
  urgent: boolean
}

export type SalesPoint = { day: string; orders: number; total: number }

export type Mover = {
  variant_id: number
  product_title: string
  variant_label: string
  qty: number
}

export type Dashboard = {
  tiles: DashboardTile[]
  sales: SalesPoint[]
  movers: Mover[]
  /** Orders and revenue over today / 7 / 30 days, each against the window
   *  before it — built by the same server function the reports use, so the
   *  dashboard and `/hisobotlar` cannot answer the same question differently.
   *  Keys: `orders_today`, `revenue_today`, `orders_week`, `revenue_week`,
   *  `orders_month`, `revenue_month`. */
  headlines: Figure[]
}

// ------------------------------------------------------------------- reports

/**
 * One headline, and the same headline over the period before it.
 *
 * `previous` and `delta` are **null on a point-in-time figure** — what is
 * standing on the shelf today, how many cells are full. The shop keeps no
 * history of that, so there is nothing to compare against, and a screen that
 * drew an arrow there would be drawing it against a nought it invented. Null
 * means: no arrow.
 *
 * `percent` is null separately, and for a different reason: the period before
 * was nought, and "up from nothing" has no percentage. The delta is still
 * real and still gets its arrow.
 *
 * `money` and `percent_value` say how to print the integer. Everything on
 * this wire is an integer: so'm, a count, or hundredths of a per cent.
 */
export type Figure = {
  key: string
  label: string
  value: number
  previous: number | null
  delta: number | null
  percent: number | null
  money: boolean
  percent_value: boolean
}

/** What was asked for, and what it is being compared against. Echoed by the
 *  server rather than worked out here — the previous period is the server's
 *  choice (same length, immediately before) and a screen that guessed at it
 *  would eventually guess differently. */
export type ReportPeriod = {
  from_day: string
  to_day: string
  previous_from_day: string
  previous_to_day: string
  days: number
  bucket: Bucket
}

export type Bucket = "day" | "week" | "month"

export type SalesBucket = {
  day: string
  label: string
  orders: number
  delivered: number
  cancelled: number
  returned: number
  revenue: number
  refunds: number
}

export type SplitRow = {
  key: string
  label: string
  orders: number
  revenue: number
  previous_orders: number
  previous_revenue: number
}

export type SalesReport = {
  period: ReportPeriod
  headlines: Figure[]
  buckets: SalesBucket[]
  by_payment: SplitRow[]
  by_delivery: SplitRow[]
  /** Delivered orders with no `delivered` event to bucket by. Anything but
   *  nought means the revenue series understates itself by that many orders,
   *  and the screen says so rather than drawing a chart it knows is short. */
  delivered_without_a_time: number
}

export type MoneyBucket = {
  day: string
  label: string
  money_in: number
  money_out: number
  refunds: number
  /** Cash in less cash out. **Not profit** — one market run landing on the
   *  3rd puts a month's buying into one day. */
  difference: number
}

export type MarketSpend = {
  place: string
  runs: number
  units: number
  cost: number
  previous_cost: number
}

export type BuyerSpend = {
  buyer_id: number | null
  name: string
  runs: number
  cost: number
  previous_cost: number
}

/**
 * Gross margin, and how much of the period it could actually see.
 *
 * `revenue` and `cost` cover only the lines that carry a cost, so the
 * percentage between them is real — and `units_costed` against `units` is
 * what says how much of the period that was. `known_from` is the day the
 * first costed order was placed; null means no order anywhere carries a cost
 * yet and the whole block is unknowable, not nought.
 */
export type Margin = {
  revenue: number
  cost: number
  margin: number
  /** Hundredths of a per cent. Null when nothing costed was sold. */
  margin_percent: number | null
  units: number
  units_costed: number
  coverage_percent: number
  known_from: string | null
}

export type MoneyReport = {
  period: ReportPeriod
  headlines: Figure[]
  buckets: MoneyBucket[]
  by_market: MarketSpend[]
  by_buyer: BuyerSpend[]
  margin: Margin
}

export type CustomerBucket = {
  day: string
  label: string
  signups: number
  orders: number
  first_orders: number
  repeat_orders: number
}

export type CustomerRank = {
  user_id: number
  name: string
  phone: string
  orders: number
  /** Delivered so'm over their whole life, not over the period — a call list
   *  is about who is worth ringing. */
  spent: number
  last_order_at: string | null
  days_since: number
}

export type CustomersReport = {
  period: ReportPeriod
  headlines: Figure[]
  buckets: CustomerBucket[]
  top_customers: CustomerRank[]
  lapsed: CustomerRank[]
  lapsed_after_days: number
}

export type ProductSale = {
  product_id: number | null
  title: string
  units: number
  revenue: number
  previous_units: number
  previous_revenue: number
  delta_units: number
  delta_revenue: number
}

export type VariantSale = {
  variant_id: number
  product_id: number | null
  product_title: string
  variant_label: string
  units: number
  revenue: number
  previous_units: number
  stock_left: number
  /** Hundredths of a per cent: sold against sold plus what is left. Null
   *  when neither sold nor stocked. */
  sell_through_percent: number | null
}

export type DeadStock = {
  variant_id: number
  product_id: number | null
  product_title: string
  variant_label: string
  stock_left: number
  unit_price: number
  shelf_value: number
  last_delivered_at: string | null
}

export type ProductsReport = {
  period: ReportPeriod
  headlines: Figure[]
  products: ProductSale[]
  variants: VariantSale[]
  rising: ProductSale[]
  falling: ProductSale[]
  dead_stock: DeadStock[]
  dead_after_days: number
}

export type StockKind = {
  kind: LocationKind
  label: string
  units: number
  value: number
  variants: number
}

export type Stocktake = {
  counts: number
  lines: number
  lines_wrong: number
  expected_units: number
  counted_units: number
  miscounted_units: number
  /** Hundredths of a per cent. **Null when nothing was counted** — a hundred
   *  per cent accuracy over nought lines is the most misleading number
   *  available here, and nought per cent is a slander. */
  accuracy_percent: number | null
}

export type StockReport = {
  period: ReportPeriod
  headlines: Figure[]
  by_kind: StockKind[]
  cells: number
  cells_full: number
  cells_empty: number
  stocktake: Stocktake
  previous_stocktake: Stocktake
}

export type CourierRow = {
  courier_id: number
  name: string
  phone: string
  attempts: number
  delivered: number
  failed: number
  /** Hundredths of a per cent. Null when they knocked on no doors. */
  success_percent: number | null
  cash_collected: number
  previous_delivered: number
}

export type ReasonRow = {
  reason: string
  count: number
  previous: number
  /** Hundredths of a per cent of this period's total. */
  share_percent: number
}

export type Duration = {
  key: string
  label: string
  samples: number
  average_minutes: number | null
  median_minutes: number | null
  previous_average_minutes: number | null
}

export type OperationsReport = {
  period: ReportPeriod
  headlines: Figure[]
  couriers: CourierRow[]
  failure_reasons: ReasonRow[]
  return_reasons: ReasonRow[]
  durations: Duration[]
}

// ------------------------------------------------------------- scan + labels

/** One printable roll label: the older label shape plus the two halves of the
 *  sticker's face — at 58 × 40 mm the size is the biggest thing on it and the
 *  colour sits beside it, so they arrive apart rather than glued into
 *  `variant_label` — and how many stickers this line is worth. */
export type RollProductLabel = ProductLabel & {
  colour: string
  size: string
  copies: number
}

export type LabelRollSheet = { products: RollProductLabel[]; cells: CellLabel[] }

/** What a scanned goods label names. `places` may be empty — the receiving
 *  desk scans labels on goods that are not booked in yet, and an empty list
 *  is an answer there, not a miss. */
export type ScanVariant = WhereIs & { colour: string; size: string }

/**
 * `GET /warehouse/scan` — one answer for whatever the gun or the camera read,
 * on every warehouse screen. Always HTTP 200: `kind: "none"` is a mis-scan,
 * which is a normal minute of warehouse work, and the screen says so loudly
 * and keeps listening rather than treating it as an error.
 */
export type ScanAnswer = {
  kind: "variant" | "cell" | "none"
  code: string
  variant: ScanVariant | null
  cell: LocationDetail | null
}

// ---------------------------------------------- the card form's reference data
//
// §5.3: the palette and the size systems are rows in the database, not a list
// in a component. A shop that starts selling belts adds a row; nobody ships a
// build. Both are read under `/admin/*` — there is no customer-facing door.

/**
 * One colour in the palette, as the picker draws it.
 *
 * `hex` may be empty — a colour no single swatch describes, like a melange —
 * and the picker falls back to a hatched square rather than painting black.
 *
 * `spellings` is every variation that folds onto this colour's key in the
 * words that are actually on variants. The form does not use it; the merge
 * screen does, and it arrives on the same read.
 */
export type ColourSwatch = {
  id: number
  slug: string
  name: string
  hex: string
  sort: number
  variant_count: number
  spellings: string[]
}

/**
 * A run of sizes, with the values it offers.
 *
 * `family` and `scale` are apart from `name` on purpose: the picker draws
 * *Erkaklar poyabzali* once with EUR/UK/US/RUS under it, rather than splitting
 * a display string on a space — a rule that breaks on the first system called
 * `Kamar`. Either may be empty.
 */
export type SizeSystem = {
  id: number
  slug: string
  name: string
  family: string
  scale: string
  sort: number
  values: string[]
  card_count: number
}

/**
 * What a card is numbered in — and `null` means **sizeless**, not unset.
 *
 * §6.3: a card is sized or sizeless and never both. This is the field that
 * says which, and it has its own door because it is that either/or rather
 * than another text box on the edit form.
 */
export type ProductSizeSystem = {
  product_id: number
  size_system: SizeSystem | null
}

/** A make, with every spelling it answers to. `GET /admin/brands`. */
export type AdminBrand = {
  id: number
  slug: string
  name: string
  product_count: number
  aliases: string[]
}

// ------------------------------------------------------ receiving (receipts)

/**
 * One receipt whose goods are labelled and still standing in QABUL — the
 * second moment's queue.
 *
 * It carries the colour because one receipt is one colour: two runs of the
 * same card an hour apart are "Nike Air · Oq" and "Nike Air · Qora", and a
 * queue that draws both as the card's name is a queue where the wrong row
 * gets shelved into the right cell. `colour_hex` is the palette's own value,
 * so the row shows a swatch rather than a word somebody has to trust.
 */
export type ReceiptWaiting = {
  id: number
  code: string
  product_id: number | null
  product_title: string
  colour: string
  colour_hex: string
  quantity: number
  age_minutes: number
}

/**
 * What came back out of the receiving area when a receipt was unsaid.
 *
 * `quantity` is what moved on *this* call and nought when the receipt had
 * already been cancelled — the same politeness the shelve door shows, for the
 * same reason: a second tap is not a mistake to shout about. `message` is the
 * sentence to put on the screen either way.
 */
export type ReceiptCancelled = {
  receipt_id: number
  run_code: string
  quantity: number
  message: string
}
