org.gradle.jvmargs=-Xmx768m -XX:MaxMetaspaceSize=192m
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.daemon=false
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.daemon.jvm.options=-Xmx384m
kotlin.incremental=false
org.gradle.tooling.parallel=false
