"""baseline: the schema create_all had been building

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-07 15:57:00.812771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Every ``sa.Enum`` above is a VARCHAR with a CHECK on SQLite and a real
# ``CREATE TYPE`` on Postgres. Twenty-four columns, twenty-one types — three
# of the types are used by more than one table.
#
# They are listed here because ``DROP TABLE`` does **not** drop the type a
# column used, and nothing in the autogenerated downgrade knew that. Left
# behind, the next ``upgrade head`` dies on
# ``type "userrole" already exists`` — so ``downgrade base`` followed by
# ``upgrade head`` worked on SQLite and was a dead end on Postgres.
#
# Written out rather than read from ``SQLModel.metadata``: a migration is a
# record of what this revision did, and one that asks today's models what to
# drop would change meaning underneath itself the next time an enum is added.
POSTGRES_ENUM_TYPES = (
    "attemptresult", "cardstatus", "deliverykind",
    "language", "notificationkind", "orderstatus",
    "paymentmethod", "pickuprunstatus", "productstatus",
    "removalreason", "removalstatus", "returnstatus",
    "reviewstatus", "settlementstatus", "shiftstatus",
    "statementlinekind", "stockcountstatus", "stockmovementkind",
    "supplystatus", "userrole", "variantkind",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kicker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gradient_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gradient_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    op.create_table('cancel_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('requires_comment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_quick_link', sa.Boolean(), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('delivery_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('express', sa.Boolean(), nullable=False),
    sa.Column('capacity_left', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_slots_day'), ['day'], unique=False)

    op.create_table('faq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fulfilment_tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_grams', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('storage_per_day', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fulfilment_tariffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fulfilment_tariffs_max_grams'), ['max_grams'], unique=False)

    op.create_table('home_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('layout', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('home_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_home_sections_key'), ['key'], unique=True)

    op.create_table('legal_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_docs_slug'), ['slug'], unique=True)

    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_phone'), ['phone'], unique=False)

    op.create_table('pickup_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hours', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('popular_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('percent_off', sa.Integer(), nullable=False),
    sa.Column('amount_off', sa.Integer(), nullable=False),
    sa.Column('min_total', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_codes_code'), ['code'], unique=True)

    op.create_table('return_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('requires_comment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity', 'entity_id', 'field', 'lang', name='uq_translation')
    )
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_lang'), ['lang'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('CUSTOMER', 'ADMIN', 'OPERATOR', 'WAREHOUSE', 'COURIER', 'SELLER', name='userrole'), nullable=False),
    sa.Column('pin_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('biometrics_enabled', sa.Boolean(), nullable=False),
    sa.Column('language', sa.Enum('UZ', 'RU', 'EN', name='language'), nullable=False),
    sa.Column('location_enabled', sa.Boolean(), nullable=False),
    sa.Column('night_mode', sa.Boolean(), nullable=False),
    sa.Column('notify_order_status', sa.Boolean(), nullable=False),
    sa.Column('notify_promotions', sa.Boolean(), nullable=False),
    sa.Column('notify_price_drop', sa.Boolean(), nullable=False),
    sa.Column('notify_push', sa.Boolean(), nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('badge', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('floor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apartment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entrance_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_user_id'), ['user_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.Enum('CUSTOMER', 'ADMIN', 'OPERATOR', 'WAREHOUSE', 'COURIER', 'SELLER', name='userrole'), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)

    op.create_table('courier_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='shiftstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('cash_expected', sa.Integer(), nullable=False),
    sa.Column('cash_declared', sa.Integer(), nullable=True),
    sa.Column('cash_counted', sa.Integer(), nullable=True),
    sa.Column('counted_by_id', sa.Integer(), nullable=True),
    sa.Column('counted_at', sa.DateTime(), nullable=True),
    sa.Column('orders_delivered', sa.Integer(), nullable=False),
    sa.Column('orders_failed', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['counted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courier_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courier_shifts_courier_id'), ['courier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courier_shifts_status'), ['status'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_idempotency')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_keys_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('ORDER', 'PROMO', 'PRICE_DROP', 'REVIEW', 'PAYMENT', 'SYSTEM', name='notificationkind'), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deep_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('payment_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last4', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('holder', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiry_month', sa.Integer(), nullable=False),
    sa.Column('expiry_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', name='cardstatus'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('processor_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_cards_user_id'), ['user_id'], unique=False)

    op.create_table('pickup_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'COLLECTED', 'RECEIVED', 'CANCELLED', name='pickuprunstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pickup_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickup_runs_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_pickup_runs_courier_id'), ['courier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_runs_status'), ['status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_history_user_id'), ['user_id'], unique=False)

    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.Column('commission_percent', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sellers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sellers_user_id'), ['user_id'], unique=False)

    op.create_table('settlement_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'PAID', name='settlementstatus'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('starts_on', 'ends_on', name='uq_settlement_period')
    )
    with op.batch_alter_table('settlement_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_periods_ends_on'), ['ends_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_periods_starts_on'), ['starts_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_periods_status'), ['status'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLACED', 'PACKING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('delivery_kind', sa.Enum('COURIER', 'PICKUP', name='deliverykind'), nullable=False),
    sa.Column('address_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_meta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pickup_point_id', sa.Integer(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('delivery_day', sa.Date(), nullable=True),
    sa.Column('delivery_start', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_end', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_method', sa.Enum('CARD', 'CASH', name='paymentmethod'), nullable=False),
    sa.Column('payment_card_id', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('courier_sequence', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('delivery_fee', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('cancel_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_card_id'], ['payment_cards.id'], ),
    sa.ForeignKeyConstraint(['pickup_point_id'], ['pickup_points.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['delivery_slots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_courier_id'), ['courier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'MODERATING', 'PUBLISHED', 'REJECTED', 'ARCHIVED', name='productstatus'), nullable=False),
    sa.Column('proposed_by_id', sa.Integer(), nullable=True),
    sa.Column('moderation_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('badge', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seller', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warranty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('stock_left', sa.Integer(), nullable=False),
    sa.Column('is_original', sa.Boolean(), nullable=False),
    sa.Column('free_delivery', sa.Boolean(), nullable=False),
    sa.Column('next_day_delivery', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_proposed_by_id'), ['proposed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_status'), ['status'], unique=False)

    op.create_table('removal_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'READY', 'COLLECTED', 'CANCELLED', name='removalstatus'), nullable=False),
    sa.Column('reason', sa.Enum('UNSELLABLE', 'UNSOLD', name='removalreason'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('prepared_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prepared_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('removal_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_removal_orders_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_removal_orders_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_removal_orders_status'), ['status'], unique=False)

    op.create_table('seller_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'PAID', name='settlementstatus'), nullable=False),
    sa.Column('gross_sales', sa.Integer(), nullable=False),
    sa.Column('commission', sa.Integer(), nullable=False),
    sa.Column('fulfilment', sa.Integer(), nullable=False),
    sa.Column('refunds', sa.Integer(), nullable=False),
    sa.Column('storage', sa.Integer(), nullable=False),
    sa.Column('adjustments', sa.Integer(), nullable=False),
    sa.Column('payable', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['settlement_periods.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'seller_id', name='uq_seller_statement')
    )
    with op.batch_alter_table('seller_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seller_statements_period_id'), ['period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_statements_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seller_statements_status'), ['status'], unique=False)

    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DECLARED', 'RECEIVED', 'CANCELLED', name='supplystatus'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('declared_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplies_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_supplies_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplies_status'), ['status'], unique=False)

    op.create_table('delivery_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('DELIVERED', 'FAILED', name='attemptresult'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cash_collected', sa.Integer(), nullable=False),
    sa.Column('happened_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['courier_shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_attempts_courier_id'), ['courier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_attempts_happened_at'), ['happened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_attempts_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_attempts_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_attempts_shift_id'), ['shift_id'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_when_added', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_favorite')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Integer(), nullable=True),
    sa.Column('stock_left', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'product_id', name='uq_offer')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_seller_id'), ['seller_id'], unique=False)

    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLACED', 'PACKING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('happened_at', sa.DateTime(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('product_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_specs_product_id'), ['product_id'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('SIZE', 'COLOR', name='variantkind'), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('stock_left', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_product_id'), ['product_id'], unique=False)

    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('color_variant_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('reserved_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['color_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_items_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_reserved_until'), ['reserved_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_user_id'), ['user_id'], unique=False)

    op.create_table('offer_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('stock_left', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', 'variant_id', name='uq_offer_variant')
    )
    with op.batch_alter_table('offer_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offer_variants_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_variants_variant_id'), ['variant_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('color_variant_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('commission_percent', sa.Integer(), nullable=False),
    sa.Column('fulfilment_fee', sa.Integer(), nullable=False),
    sa.Column('variant_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['color_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_seller_id'), ['seller_id'], unique=False)

    op.create_table('removal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('removal_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('prepared_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['removal_id'], ['removal_orders.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('removal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_removal_lines_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_removal_lines_removal_id'), ['removal_id'], unique=False)

    op.create_table('stock_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='stockcountstatus'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('opened_by_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_counts_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_stock_counts_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_counts_status'), ['status'], unique=False)

    op.create_table('supply_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('declared_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supply_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_lines_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_lines_supply_id'), ['supply_id'], unique=False)

    op.create_table('return_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'REFUNDED', name='returnstatus'), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refund_amount', sa.Integer(), nullable=False),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_requests_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_requests_user_id'), ['user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('MODERATING', 'PUBLISHED', 'REJECTED', name='reviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('stock_count_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('expected', sa.Integer(), nullable=False),
    sa.Column('counted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['count_id'], ['stock_counts.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_count_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_count_lines_count_id'), ['count_id'], unique=False)

    op.create_table('pickup_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('return_request_id', sa.Integer(), nullable=False),
    sa.Column('collected', sa.Boolean(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['pickup_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'return_request_id', name='uq_pickup_line')
    )
    with op.batch_alter_table('pickup_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickup_lines_return_request_id'), ['return_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_lines_run_id'), ['run_id'], unique=False)

    op.create_table('review_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'review_id', name='uq_review_like')
    )
    with op.batch_alter_table('review_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_likes_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_likes_user_id'), ['user_id'], unique=False)

    op.create_table('statement_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('SALE', 'COMMISSION', 'FULFILMENT', 'REFUND', 'REFUND_COMMISSION', 'STORAGE', 'ADJUSTMENT', name='statementlinekind'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('return_request_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['seller_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statement_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statement_lines_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_statement_lines_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_statement_lines_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statement_lines_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statement_lines_return_request_id'), ['return_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statement_lines_statement_id'), ['statement_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('OPENING', 'INTAKE', 'SALE', 'CANCEL_RETURN', 'CUSTOMER_RETURN', 'WRITE_OFF', 'COUNT_ADJUSTMENT', 'SELLER_RETURN', name='stockmovementkind'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('supply_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('return_request_id', sa.Integer(), nullable=True),
    sa.Column('count_id', sa.Integer(), nullable=True),
    sa.Column('removal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['count_id'], ['stock_counts.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['removal_id'], ['removal_orders.id'], ),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_count_id'), ['count_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_removal_id'), ['removal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_return_request_id'), ['return_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_supply_id'), ['supply_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_variant_id'), ['variant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_variant_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_supply_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_return_request_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_removal_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_order_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_offer_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_kind'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_at'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_count_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_actor_id'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('statement_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statement_lines_statement_id'))
        batch_op.drop_index(batch_op.f('ix_statement_lines_return_request_id'))
        batch_op.drop_index(batch_op.f('ix_statement_lines_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_statement_lines_offer_id'))
        batch_op.drop_index(batch_op.f('ix_statement_lines_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_statement_lines_kind'))

    op.drop_table('statement_lines')
    with op.batch_alter_table('review_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_likes_review_id'))

    op.drop_table('review_likes')
    with op.batch_alter_table('pickup_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickup_lines_run_id'))
        batch_op.drop_index(batch_op.f('ix_pickup_lines_return_request_id'))

    op.drop_table('pickup_lines')
    with op.batch_alter_table('stock_count_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_count_lines_count_id'))

    op.drop_table('stock_count_lines')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_product_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('return_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_return_requests_order_id'))

    op.drop_table('return_requests')
    with op.batch_alter_table('supply_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_lines_supply_id'))
        batch_op.drop_index(batch_op.f('ix_supply_lines_offer_id'))

    op.drop_table('supply_lines')
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_counts_status'))
        batch_op.drop_index(batch_op.f('ix_stock_counts_offer_id'))
        batch_op.drop_index(batch_op.f('ix_stock_counts_code'))

    op.drop_table('stock_counts')
    with op.batch_alter_table('removal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_removal_lines_removal_id'))
        batch_op.drop_index(batch_op.f('ix_removal_lines_offer_id'))

    op.drop_table('removal_lines')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_seller_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_offer_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('offer_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_variants_variant_id'))
        batch_op.drop_index(batch_op.f('ix_offer_variants_offer_id'))

    op.drop_table('offer_variants')
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_cart_items_reserved_until'))
        batch_op.drop_index(batch_op.f('ix_cart_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_cart_items_offer_id'))

    op.drop_table('cart_items')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_variants_parent_id'))

    op.drop_table('product_variants')
    with op.batch_alter_table('product_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_specs_product_id'))

    op.drop_table('product_specs')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))

    op.drop_table('order_events')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_seller_id'))
        batch_op.drop_index(batch_op.f('ix_offers_product_id'))

    op.drop_table('offers')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_product_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('delivery_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_attempts_shift_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_attempts_result'))
        batch_op.drop_index(batch_op.f('ix_delivery_attempts_order_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_attempts_happened_at'))
        batch_op.drop_index(batch_op.f('ix_delivery_attempts_courier_id'))

    op.drop_table('delivery_attempts')
    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplies_status'))
        batch_op.drop_index(batch_op.f('ix_supplies_seller_id'))
        batch_op.drop_index(batch_op.f('ix_supplies_code'))

    op.drop_table('supplies')
    with op.batch_alter_table('seller_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_statements_status'))
        batch_op.drop_index(batch_op.f('ix_seller_statements_seller_id'))
        batch_op.drop_index(batch_op.f('ix_seller_statements_period_id'))

    op.drop_table('seller_statements')
    with op.batch_alter_table('removal_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_removal_orders_status'))
        batch_op.drop_index(batch_op.f('ix_removal_orders_seller_id'))
        batch_op.drop_index(batch_op.f('ix_removal_orders_code'))

    op.drop_table('removal_orders')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_status'))
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_proposed_by_id'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_index(batch_op.f('ix_products_brand_id'))

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_courier_id'))
        batch_op.drop_index(batch_op.f('ix_orders_code'))

    op.drop_table('orders')
    with op.batch_alter_table('settlement_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_periods_status'))
        batch_op.drop_index(batch_op.f('ix_settlement_periods_starts_on'))
        batch_op.drop_index(batch_op.f('ix_settlement_periods_ends_on'))

    op.drop_table('settlement_periods')
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sellers_user_id'))
        batch_op.drop_index(batch_op.f('ix_sellers_name'))

    op.drop_table('sellers')
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_history_user_id'))

    op.drop_table('search_history')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('pickup_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickup_runs_status'))
        batch_op.drop_index(batch_op.f('ix_pickup_runs_courier_id'))
        batch_op.drop_index(batch_op.f('ix_pickup_runs_code'))

    op.drop_table('pickup_runs')
    with op.batch_alter_table('payment_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_cards_user_id'))

    op.drop_table('payment_cards')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_key'))
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_created_at'))

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('courier_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courier_shifts_status'))
        batch_op.drop_index(batch_op.f('ix_courier_shifts_courier_id'))

    op.drop_table('courier_shifts')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_user_id'))

    op.drop_table('addresses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_lang'))
        batch_op.drop_index(batch_op.f('ix_translation_entity_id'))
        batch_op.drop_index(batch_op.f('ix_translation_entity'))

    op.drop_table('translation')
    op.drop_table('review_tags')
    op.drop_table('return_reasons')
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_codes_code'))

    op.drop_table('promo_codes')
    op.drop_table('popular_queries')
    op.drop_table('pickup_points')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_phone'))

    op.drop_table('otp_codes')
    with op.batch_alter_table('legal_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_docs_slug'))

    op.drop_table('legal_docs')
    with op.batch_alter_table('home_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_home_sections_key'))

    op.drop_table('home_sections')
    with op.batch_alter_table('fulfilment_tariffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fulfilment_tariffs_max_grams'))

    op.drop_table('fulfilment_tariffs')
    op.drop_table('faq_items')
    with op.batch_alter_table('delivery_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_slots_day'))

    op.drop_table('delivery_slots')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    op.drop_table('categories')
    op.drop_table('cancel_reasons')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))

    op.drop_table('brands')
    op.drop_table('banners')
    # ### end Alembic commands ###

    # And the types the tables were using. See POSTGRES_ENUM_TYPES above.
    # `IF EXISTS` so that a downgrade of a partially-built database is not a
    # second error on top of the first, and SQLite is skipped because it has
    # no such object to drop.
    if op.get_bind().dialect.name == "postgresql":
        for name in POSTGRES_ENUM_TYPES:
            op.execute(f'DROP TYPE IF EXISTS "{name}"')
