"""a receipt can be unsaid: the ledger gets a receipt_cancel

"Typed 20, meant 10" had no path. The goods were in ``QABUL``, the stickers
were printed, and the only way back was somebody editing the database — so
``StockMovementKind`` grows one value, ``RECEIPT_CANCEL``, which is the move
``POST /warehouse/receipts/{id}/cancel`` writes: out of the receiving area, to
nowhere, one row per line of the receipt.

Its own value rather than a reuse of ``WRITE_OFF`` because the two are read
differently downstream: the stock report sums write-offs into what the shop
*lost*, and a mistyped receipt is not a loss of twenty pairs of shoes — it is
twenty pairs that never arrived.

**Two dialects, two operations.** On Postgres the column is a server-side enum
type and the only thing needed is one more value in it, added the way
``3b4d3d7fc68b`` added ``SELLER``. On SQLite the column is a plain
``VARCHAR(n)`` whose ``n`` is the longest member name — ``WRITE_OFF``, nine —
so the column has to widen to fourteen or ``test_schema`` sees two schemas
that disagree. The autogenerated ``batch_alter_table`` is that widening and
nothing more; the skeleton was autogenerated, the dialect guard is not.

Revision ID: 381b0c289b97
Revises: d3bf33a0e160
Create Date: 2026-09-15 17:57:42.593459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '381b0c289b97'
down_revision: Union[str, Sequence[str], None] = 'd3bf33a0e160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Every member the enum has after this revision, in declaration order — which
# is the order SQLAlchemy writes into a Postgres type and the order the
# autogenerate diff compares against.
KINDS = (
    'RECEIPT',
    'RECEIPT_CANCEL',
    'PUTAWAY',
    'MOVE',
    'PICK',
    'HANDOVER',
    'DELIVERED',
    'RETURN',
    'RELIST',
    'DAMAGE',
    'WRITE_OFF',
    'ADJUST',
)


def upgrade() -> None:
    """One more value in the type, or one wider column."""
    bind = op.get_bind()

    if bind.dialect.name == "postgresql":
        # Alembic opened a transaction; before Postgres 12, ADD VALUE refuses
        # to run inside one. Committing here ends Alembic's transaction —
        # safe, because this upgrade does exactly one thing.
        op.execute("COMMIT")
        op.execute(
            "ALTER TYPE stockmovementkind ADD VALUE IF NOT EXISTS 'RECEIPT_CANCEL'"
        )
        return

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.alter_column(
            'kind',
            existing_type=sa.VARCHAR(length=9),
            type_=sa.Enum(*KINDS, name='stockmovementkind'),
            existing_nullable=False,
        )


def downgrade() -> None:
    """The rows first, then the value.

    A movement holding a value the application can no longer read is a row
    that raises on the way out of the database, so it is rewritten on every
    dialect before anything else happens — and on SQLite it *must* be, because
    the column narrows back to nine characters underneath it.

    ``WRITE_OFF`` is where they go: it is the nearest surviving kind — goods
    that left the building and are not coming back — and the reason string on
    every such row still says which receipt was called off. The distinction
    this revision exists to draw is the thing a downgrade spends.
    """
    bind = op.get_bind()

    op.execute(
        "UPDATE stock_movements SET kind = 'WRITE_OFF' "
        "WHERE kind = 'RECEIPT_CANCEL'"
    )

    if bind.dialect.name == "postgresql":
        # There is no ALTER TYPE ... DROP VALUE: build the eleven-value type
        # the baseline had, swing the column over, drop the twelve-value one.
        old = ", ".join(f"'{name}'" for name in KINDS if name != 'RECEIPT_CANCEL')
        op.execute("ALTER TYPE stockmovementkind RENAME TO stockmovementkind_old")
        op.execute(f"CREATE TYPE stockmovementkind AS ENUM ({old})")
        op.execute(
            "ALTER TABLE stock_movements ALTER COLUMN kind "
            "TYPE stockmovementkind USING kind::text::stockmovementkind"
        )
        op.execute("DROP TYPE stockmovementkind_old")
        return

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.alter_column(
            'kind',
            existing_type=sa.Enum(*KINDS, name='stockmovementkind'),
            type_=sa.VARCHAR(length=9),
            existing_nullable=False,
        )
