"""a variant can leave the shop window without being erased

A cell is deletable only while nothing has ever moved through it, which is
right — every movement, placement and order line points at it. But that left a
size received by mistake as a struck-through chip on the product page for the
life of the card, with no way to remove it. `retired` stops the offer and keeps
the ledger, and is allowed only on a cell that holds nothing.

Revision ID: 4a0d0f4cfc4a
Revises: 55a4f0b70cde
Create Date: 2026-09-10 08:47:11.325497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a0d0f4cfc4a'
down_revision: Union[str, Sequence[str], None] = '55a4f0b70cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `server_default` because the table already has rows: a NOT NULL column
    # added without one fails on every database that is not empty, and the
    # place that fails is somebody's upgrade rather than this review. Dropped
    # again immediately, so this schema matches the one `create_all` builds
    # from the models — which is what `test_schema` checks.
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'retired',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('retired', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_column('retired')

    # ### end Alembic commands ###
