"""A home rail says which products, not only how they are drawn

``layout`` was doing two jobs. Anything that was not ``deals`` came back in
sold-count order, so "Yangi keldi" and "Ko'p olinadi" answered with the same
products in the same order — which reads as a broken screen, not as two rails.
``pick`` is the selection rule (``new`` | ``popular`` | ``deals``) and
``layout`` stays the presentation.

Added with a ``server_default`` because the table has rows and the column is
``NOT NULL``, then dropped again so this schema matches the one `create_all`
builds from the models.

Revision ID: 5211b6785972
Revises: c5268d8e8a1d
Create Date: 2026-09-09 14:26:03.124534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5211b6785972'
down_revision: Union[str, Sequence[str], None] = 'c5268d8e8a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_sections', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'pick',
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default='popular',
            )
        )

    with op.batch_alter_table('home_sections', schema=None) as batch_op:
        batch_op.alter_column('pick', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_sections', schema=None) as batch_op:
        batch_op.drop_column('pick')

    # ### end Alembic commands ###
