"""An order line keeps the colour and the size apart

`variant_label` joins them with a dot for a line with one line to spare, and a
client holding only that prints "Qora · 41" as though it were the name of one
thing. Both columns are snapshotted for the same reason the label is: the
variant may be gone by the time somebody opens the order again.

`server_default=''` because the table has rows and the columns are NOT NULL;
dropped again afterwards so this schema matches what `create_all` builds.

Revision ID: 55a4f0b70cde
Revises: 5211b6785972
Create Date: 2026-09-09 15:27:43.022138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55a4f0b70cde'
down_revision: Union[str, Sequence[str], None] = '5211b6785972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'colour',
                sqlmodel.sql.sqltypes.AutoString(length=60),
                nullable=False,
                server_default='',
            )
        )
        batch_op.add_column(
            sa.Column(
                'size',
                sqlmodel.sql.sqltypes.AutoString(length=40),
                nullable=False,
                server_default='',
            )
        )

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('colour', server_default=None)
        batch_op.alter_column('size', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('colour')

    # ### end Alembic commands ###
