"""a sold unit remembers what it cost

Margin was not a figure this system could produce. `order_items` froze the
price and nothing about the cost; the `delivered` movement carries no supply
id, so a sold unit could not be traced back to a lot. `products.last_cost` is a
*function* answering the newest supply line for a whole card — a pricing aid
for the card editor, product-level, and `sort_run` deletes and re-inserts lines
so the ids lie about which is newest. Nothing could be built on it.

Two columns close it. `product_variants.last_cost` is what the newest lot of
*that cell* cost, kept by `app.stock.move` on every receipt. `order_items`
snapshots it at checkout beside `unit_price`, frozen for ever the same way.
Gross margin per order, per product, per category and per day is then one join.

**Nought means unknown, never free.** Every row that exists when this runs gets
a nought, and a report that read that as a cost of zero would print a hundred
per cent margin on the shop's whole history. `app.routers.reports` counts only
lines that carry a cost, and says beside every margin how much of the period it
could see and from which day the figure is real.

Revision ID: 7ecba331552f
Revises: 90f05cf05741
Create Date: 2026-09-11 15:37:43.433422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7ecba331552f'
down_revision: Union[str, Sequence[str], None] = '90f05cf05741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `server_default` because both tables already have rows: a NOT NULL column
    # added without one fails on every database that is not empty, and the
    # place it fails is somebody's upgrade rather than this review. Dropped
    # again immediately, so this schema matches the one `create_all` builds
    # from the models — which is what `test_schema` checks.
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'unit_cost', sa.Integer(), nullable=False, server_default='0'
            )
        )

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('unit_cost', server_default=None)

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'last_cost', sa.Integer(), nullable=False, server_default='0'
            )
        )

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('last_cost', server_default=None)

    # No backfill. `supply_lines` knows what every lot cost and it would be
    # possible to walk them and seed `last_cost` from the newest — but a
    # backfilled cost stamped onto orders that were placed months earlier is a
    # margin figure invented after the fact, and it would be indistinguishable
    # from a real one. The past stays unknown and says so.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Both costs are lost coming back down, and that is the honest outcome: the
    # column is the only place either figure lives. Reversible in the sense
    # that matters — the schema returns to exactly what the revision below
    # built, so a bad deploy can be rolled back without a restore.
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_column('last_cost')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('unit_cost')

    # ### end Alembic commands ###
