"""the userrole enum loses the seller

`UserRole.SELLER` is deleted from the application: there is one shop, and the
person who photographs the goods is the person who sells them, so everything
the role guarded — the shop window, the order queue, the dashboard — is the
admin's now. A value the code no longer names must come out of the database
type too, or the next `sa.Enum` autogenerate diff will disagree with the
server for ever.

**Postgres cannot drop an enum value.** `3b4d3d7fc68b` added `'SELLER'` with
`ADD VALUE` and documented that the road back is a type rebuild; this is that
rebuild, done deliberately rather than in a rollback. The order matters:

1. any row still holding `'SELLER'` is moved to `'ADMIN'` first — in this
   shop the seller's work was always the owner's work, and a cast with the
   value still present would abort the whole migration;
2. the old type is renamed aside, a new `userrole` is created without the
   value, and both columns that use it — `users.role` and
   `audit_log.actor_role` — are rewritten onto it through a text cast;
3. the old type is dropped.

The rewrite takes an exclusive lock on both tables; they are small here and
the alternative is a phantom value in every future schema comparison.

**A no-op on SQLite**, where an enum column is a plain VARCHAR with no
server-side value list — the same dialect guard `3b4d3d7fc68b` used. The row
rewrite of step 1 still runs there: SQLite will happily keep holding a value
the application can no longer read, and one such row would sign in as a 500.

The skeleton was autogenerated for the id/down_revision wiring; the enum
surgery is explicit `op.execute`, because there is no `op.*` operation for
rebuilding a Postgres enum and autogenerate cannot see server-side types on
the SQLite database development runs against.

Revision ID: 8a32e11a5130
Revises: 3b4d3d7fc68b
Create Date: 2026-09-14 16:21:26.680694

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8a32e11a5130'
down_revision: Union[str, Sequence[str], None] = '3b4d3d7fc68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Move any seller to admin, then rebuild `userrole` without SELLER."""
    bind = op.get_bind()

    # The rows first, on every dialect: the enum member is gone from the code,
    # so a row holding it is unreadable whatever the column type is. Stored by
    # *name* — SQLAlchemy maps a Python enum by name, so the rows say 'SELLER'.
    op.execute("UPDATE users SET role = 'ADMIN' WHERE role = 'SELLER'")
    op.execute(
        "UPDATE audit_log SET actor_role = 'ADMIN' WHERE actor_role = 'SELLER'"
    )

    if bind.dialect.name != "postgresql":
        # SQLite stores the column as text; there is no server-side value
        # list to rebuild.
        return

    # There is no ALTER TYPE ... DROP VALUE: build the four-value type the
    # baseline had, swing both columns over, drop the five-value one.
    op.execute("ALTER TYPE userrole RENAME TO userrole_old")
    op.execute(
        "CREATE TYPE userrole AS ENUM ('CUSTOMER', 'ADMIN', 'WAREHOUSE', 'COURIER')"
    )
    op.execute(
        "ALTER TABLE users ALTER COLUMN role "
        "TYPE userrole USING role::text::userrole"
    )
    op.execute(
        "ALTER TABLE audit_log ALTER COLUMN actor_role "
        "TYPE userrole USING actor_role::text::userrole"
    )
    op.execute("DROP TYPE userrole_old")


def downgrade() -> None:
    """Put the value back, the way `3b4d3d7fc68b` first added it.

    The accounts that were moved to admin stay admin: which users held the
    role is information the upgrade deliberately spent, and inventing sellers
    on the way down would be worse than having none.
    """
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    # Alembic opened a transaction; before Postgres 12, ADD VALUE refuses to
    # run inside one. Committing here ends Alembic's transaction — safe,
    # because this downgrade does exactly one thing.
    op.execute("COMMIT")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'SELLER'")
