"""Cards a customer may pay with, and the charge's own name

Revision ID: 90f05cf05741
Revises: 4a0d0f4cfc4a
Create Date: 2026-09-10 14:09:49.824432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90f05cf05741'
down_revision: Union[str, Sequence[str], None] = '4a0d0f4cfc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last4', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('holder', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiry_month', sa.Integer(), nullable=False),
    sa.Column('expiry_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', name='cardstatus'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('processor_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_cards_user_id'), ['user_id'], unique=False)

    # Added with a default and then stripped of it.
    #
    # There are orders in this table already and none of them has a charge
    # reference, so a NOT NULL column with nothing to put in it is a migration
    # that fails on the first database anybody has used. The default fills
    # those rows in — and then goes, because `models.py` does not declare one
    # and `test_alembic_builds_the_same_schema_as_create_all` compares the two
    # schemas column for column. A default left behind here is a difference
    # between what Alembic builds and what the models describe, which is
    # exactly the drift that test exists to catch.
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'payment_reference',
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default='',
            )
        )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column(
            'payment_reference',
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
            server_default=None,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_reference')

    with op.batch_alter_table('payment_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_cards_user_id'))

    op.drop_table('payment_cards')
    # ### end Alembic commands ###
