"""the colour palette and the size systems

Revision ID: a00aab6b8237
Revises: a91d2fc3352c
Create Date: 2026-09-15 14:15:02.222925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a00aab6b8237'
down_revision: Union[str, Sequence[str], None] = 'a91d2fc3352c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The foreign key products.size_system_id -> size_systems.id, named.
#
# Autogenerate wrote `create_foreign_key(None, ...)` and, in `downgrade`,
# `drop_constraint(None, type_='foreignkey')`. The first works; the second
# raises `ValueError: Constraint must have a name` the moment anybody runs it,
# on SQLite and on Postgres alike — so the migration would have been a
# one-way door that only announced it at the worst possible time. A name is
# also what makes the Postgres drop a single statement rather than a lookup in
# `information_schema`.
#
# The name is not in `models.py` and does not need to be: `tools.schema_diff`
# deliberately ignores foreign key names, because SQLite's `create_all` leaves
# them unnamed and no SQLite statement can refer to one.
FK_SIZE_SYSTEM = "fk_products_size_system_id"


def upgrade() -> None:
    """Three reference tables, and the column on a card that names one.

    **No rows are written here.** The palette and the size systems arrive
    through `python -m app.seed`, which is idempotent on the colour's key and
    the system's slug and is already how the room's cells reach a database
    that was built before the fourth rack existed. Seeding from a migration
    would put the shop's vocabulary in two places, and the copy in
    `alembic/versions` would be the one nobody could edit.

    So on an existing database the pickers are empty until the seed is run.
    That is the same sentence as "a new rack is a line in `app.locations` and
    a second seed run", and it is the deployment step, not an accident.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('hex', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colours_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_colours_slug'), ['slug'], unique=True)

    op.create_table('size_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('family', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('scale', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('size_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_size_systems_slug'), ['slug'], unique=True)

    op.create_table('size_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['size_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'value', name='uq_size_value')
    )
    with op.batch_alter_table('size_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_size_values_system_id'), ['system_id'], unique=False)

    # Nullable, and it stays nullable: null is not "not filled in yet", it is
    # **sizeless** (§6.3). Every card that already exists is therefore
    # correctly described the moment this runs, with nothing to backfill —
    # a card's sizes are on its variants and are not moved by this.
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_system_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_size_system_id'), ['size_system_id'], unique=False)
        batch_op.create_foreign_key(FK_SIZE_SYSTEM, 'size_systems', ['size_system_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Back to no palette — and the palette goes with it.

    `drop_table` takes the rows, which here means every colour and every size
    somebody typed into the admin panel. That is the honest cost of undoing
    this and it is why `backend/README.md` says to copy the database first.
    Nothing on a card is lost: `products.size_system_id` is the only thing
    pointing at these tables, and a card's actual sizes live on its variants.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(FK_SIZE_SYSTEM, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_products_size_system_id'))
        batch_op.drop_column('size_system_id')

    with op.batch_alter_table('size_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_size_values_system_id'))

    op.drop_table('size_values')
    with op.batch_alter_table('size_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_size_systems_slug'))

    op.drop_table('size_systems')
    with op.batch_alter_table('colours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colours_slug'))
        batch_op.drop_index(batch_op.f('ix_colours_key'))

    op.drop_table('colours')
    # ### end Alembic commands ###
