"""A card can be a receiving-desk stub

A pile off the van has a name, a colour, sizes and counts, and nothing else
that is true yet — so ``category_id`` becomes nullable and two columns arrive:
``kind``, the word the desk used, which is where the receiving form's chips
come from, and ``snapshot_url``, the identification photograph taken over the
open sack. Requiring a category to write a card is what stopped the goods
reaching the shelf.

The two new columns carry a ``server_default`` of the empty string. They are
``NOT NULL`` and this database has rows: without one, ``ADD COLUMN`` has
nothing to put in them and the upgrade fails on somebody else's machine rather
than here.

Revision ID: c5268d8e8a1d
Revises: 474db20bb4f8
Create Date: 2026-09-09 11:24:40.114022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5268d8e8a1d'
down_revision: Union[str, Sequence[str], None] = '474db20bb4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'kind',
                sqlmodel.sql.sqltypes.AutoString(length=60),
                nullable=False,
                server_default='',
            )
        )
        batch_op.add_column(
            sa.Column(
                'snapshot_url',
                sqlmodel.sql.sqltypes.AutoString(length=300),
                nullable=False,
                server_default='',
            )
        )
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_products_kind'), ['kind'], unique=False)

    # And then dropped again. The default existed to fill the existing rows;
    # leaving it behind would mean this schema and the one `create_all` builds
    # from the models disagree, which the parity test in the suite catches —
    # the application supplies the empty string itself.
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('kind', server_default=None)
        batch_op.alter_column('snapshot_url', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_kind'))
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('snapshot_url')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
