"""the courier app: a stop has a pin, and the cash comes back

Revision ID: d3bf33a0e160
Revises: e19dd560fe2f
Create Date: 2026-09-15 15:00:18.674683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3bf33a0e160'
down_revision: Union[str, Sequence[str], None] = 'e19dd560fe2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Two halves of one app, and they land together because they shipped
    together.

    **`orders.latitude` / `orders.longitude`.** The order snapshotted the words
    for an address and not the pin, so a round could be listed and could not be
    drawn. Nullable, and **nothing backfills them**: an address saved without a
    pin has none, every order placed before this revision has none, and a
    guessed coordinate on a delivery record is worse than an absent one — it
    would send a courier somewhere with the confidence of a fact. Everything
    reading them treats null as "no pin" and keeps the stop.

    **`cash_handovers`.** There was no way for a courier's cash on hand to go
    down: it was the sum of every door they had ever knocked on, which is only
    true on their first day. A hand-in is an event with a time on it naming
    both hands, so it is a table rather than a counter on `users` — the
    question anybody actually asks is "who had Tuesday's takings", and a number
    that gets reset cannot answer it.

    An empty table on every existing database, which is correct: nobody has
    handed anything in through a door that did not exist, and inventing rows to
    balance a historic figure would be inventing receipts.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('received_by_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('happened_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_handovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_handovers_courier_id'), ['courier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_handovers_happened_at'), ['happened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_handovers_received_by_id'), ['received_by_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    The columns before the table, which is the reverse of the order above: a
    downgrade is read by somebody in a hurry, and the two halves are unrelated,
    so the only thing that matters is that each one undoes itself completely.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('cash_handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_handovers_received_by_id'))
        batch_op.drop_index(batch_op.f('ix_cash_handovers_happened_at'))
        batch_op.drop_index(batch_op.f('ix_cash_handovers_courier_id'))

    op.drop_table('cash_handovers')
    # ### end Alembic commands ###
