"""the description keeps its words beside its markup

Revision ID: e19dd560fe2f
Revises: e4b6e8789f84
Create Date: 2026-09-15 14:51:55.384408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e19dd560fe2f'
down_revision: Union[str, Sequence[str], None] = 'a00aab6b8237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'description_text',
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                # Autogenerate wrote no default. A NOT NULL column added to a
                # table that already has rows needs one, or the add is refused
                # on every existing database — which is all of them.
                server_default='',
            )
        )

    # ### end Alembic commands ###

    # Every description written before this revision is plain text already, so
    # the words are the description. Without this the search stops matching
    # descriptions the moment the column becomes the one it reads, and it fails
    # silently: nobody gets an error, results simply stop appearing.
    op.execute("UPDATE products SET description_text = description")

    # And now drop the default, the way `7ecba331552f` and `5211b6785972` do.
    # It was scaffolding for the existing rows; leaving it behind would put a
    # default in the migrated schema that `SQLModel.metadata.create_all` does
    # not put in the model's, and `test_alembic_builds_the_same_schema_as_
    # create_all` is there to catch exactly that drift.
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('description_text', server_default=None)


def downgrade() -> None:
    """Downgrade schema.

    The markup stays in `description`, so nothing written since is lost by
    going back — only the words beside it, which are derived and can be
    rebuilt by writing each card once.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('description_text')

    # ### end Alembic commands ###
