"""a brand answers to every spelling it has had

The receiving desk types the make as free text and `_brand_named` matched it
case-insensitively against `brands.name`, writing a new row when it found
nothing. So every novel spelling was a permanent brand, and — worse — the name
column was the *only* thing a spelling could be matched against: correcting
`On Cloud` to `On Running` in the admin panel detached the row from every sack
that would be typed the old way, so the next van wrote the duplicate straight
back and undid the correction.

`brand_aliases` is what a brand answers to, as against what it is called. One
row per spelling — the current name, the names it has been renamed away from,
the names of every brand merged into it — with `key` the spelling flattened for
case and punctuation, unique across the whole table so one spelling means one
make. See `app.brands`.

**Every existing brand is backfilled with its own name**, because the lookup
now goes through this table and a brand with no alias row is a brand the desk
can no longer find — which would mean a duplicate of every make in the
catalogue on the first evening after the deploy. Where two existing rows
flatten to one key only the first keeps it: they are the duplicate this table
exists to make mergeable, the second is reachable by slug in the admin panel,
and silently pointing one spelling at two rows is the thing the unique index
is here to prevent.

Revision ID: efe41db38f4a
Revises: 7ecba331552f
Create Date: 2026-09-11 16:17:33.919271

"""
import re
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `sqlmodel.sql.sqltypes.AutoString()` for every `str`
# field, because that is the type SQLModel put on the column. Without this
# import the generated file is a NameError waiting for whoever runs it — and
# it fails at `upgrade`, on their database, not at review time. Imported
# unconditionally rather than left to `${imports}`: a migration that
# happens to touch no string column does not need it, and an unused import is
# a much smaller problem than a broken one.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'efe41db38f4a'
down_revision: Union[str, Sequence[str], None] = '7ecba331552f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_aliases_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_aliases_key'), ['key'], unique=True)

    # ### end Alembic commands ###

    _backfill_one_alias_per_brand()


def _backfill_one_alias_per_brand() -> None:
    """Give every brand that already exists its own name to answer to.

    Without this the receiving desk finds nothing for a make it has been
    booking in for months and writes a second row for it — on the first
    evening after the deploy, for every make in the catalogue. A schema change
    that quietly duplicates the data it was meant to de-duplicate.

    The key rule is copied here rather than imported from ``app.brands``. A
    migration is a statement about a database at a moment in time, and a
    migration that calls into application code is a migration whose meaning
    changes the next time somebody edits that code — the rows this run wrote
    would then disagree with the rows the next run writes.
    """
    bind = op.get_bind()
    brands = bind.execute(sa.text("SELECT id, name FROM brands ORDER BY id")).fetchall()
    seen: set[str] = set()
    for brand_id, name in brands:
        key = " ".join(re.sub(r"[\W_]+", " ", name or "", flags=re.UNICODE).casefold().split())
        if not key or key in seen:
            continue
        seen.add(key)
        bind.execute(
            sa.text(
                "INSERT INTO brand_aliases (brand_id, name, key) "
                "VALUES (:brand_id, :name, :key)"
            ),
            {"brand_id": brand_id, "name": name, "key": key},
        )


def downgrade() -> None:
    """Downgrade schema.

    The spellings are lost, and that is the honest outcome: this table is the
    only place they live. What comes back is exactly the schema the revision
    below builds — the lookup falls back to matching on ``brands.name``, which
    is what it did before — so a bad deploy rolls back without a restore, at
    the cost of forgetting which words used to point where.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_aliases_key'))
        batch_op.drop_index(batch_op.f('ix_brand_aliases_brand_id'))

    op.drop_table('brand_aliases')
    # ### end Alembic commands ###
